### ISSUE TITLE
服务经常会挂掉

### ISSUE THREAD

**Issue by sicode** [uje/DynamicDNS#4]
第一种情况，在获取IP地址连续失败后，服务会完全终止，必须手动重启服务才可以
第二种情况，这种就比较莫名奇妙了，日志上也看不出什么眉目出来，目前找不出原因~

**Comment by uje** [comment]
问题1，应该是dnspod报的错才会退出，你可以登录dnspod后台查看日志。

**Comment by uje** [comment]
1

**Comment by ghost** [comment]
也遇到这问题，看起来似乎是问题1，但我不确定。确实前面似乎有断网连续不能得到ip地址。
