### ISSUE TITLE
dnspod升级导致无法使用

### ISSUE THREAD

**Issue by lanybass** [uje/DynamicDNS#8]
近期dnspod已停止使用对tls1.2以前的版本支持，所以此程序的api请求发生错误。  
发请求需要改为tls1.2，我已修改并测试过了，改了就可以。  
在请求之前设置tls1.2:  
https://github.com/uje/DynamicDNS/blob/f37bb97c904a5d12f2c6c7e2d890c55dbfe36052/DNSPod.Api/Core/RequestBase.cs#L94  
之前增加  
`ServicePointManager.SecurityProtocol = (SecurityProtocolType)192 | (SecurityProtocolType)768 | (SecurityProtocolType)3072;`  
所有项目.net版本改为4.5

**Comment by lanybass** [comment]
by the way,你内置的获取外网ip的api，只有一个可用了，可以换其他的。
我用ip138的还挺快

**Comment by uje** [comment]
感谢提醒，已经修复
